### ISSUE TITLE
uint32_t vs uint64_t error in CUDA 10.2 build

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#194] opened 2020-05-07 20:20 UTC
```
[ 78%] building cxx object lonestar/analytics/cpu/pagerank/cmakefiles/pagerank-pull.dir/pagerank-pull.cpp.o
/data/lonestar/analytics/gpu/sgd/sgdgraphcu.h(154): error: argument of type "uint32_t *" is incompatible with parameter of type "__uint64_t"
          detected during instantiation of "void sgd_lc_lineararray_undirected_graph<nodedataty, edgedataty>::read(const char *) [with nodedataty=unsigned int, edgedataty=edgedatatype]"
/data/lonestar/analytics/gpu/sgd/sgdasyncedgecu.h(358): here
```

Example: https://app.circleci.com/pipelines/github/IntelligentSoftwareSystems/Galois/384/workflows/ea8967fe-9e9f-4bea-9bb3-7eb4be31418d/jobs/7619/steps

**Comment by vishweshjatala** [comment] 2020-05-11 17:47
Assigning to @chenxuhao  as it is related with sgd.

**Comment by vishweshjatala** [comment] 2020-05-14 21:23
This test builds correctly on our local machine. It seems to be failing only on Ubuntu18.04. I don't have access to Ubuntu 18.04. Is there a way we can try to  reproduce it?

**Comment by ddn0** [comment] 2020-05-14 21:29
One way would be to use docker and just manually execute the statements here:
https://github.com/IntelligentSoftwareSystems/Galois/blob/master/.circleci/config.yml#L179
```bash
docker run --rm -it -v $(pwd):/source nvidia/cuda:10.2-devel-ubuntu18.04
...apt ...
cmake /source ...
```


The other option is to use CircleCI's option to rerun a job with ssh.

**Comment by vishweshjatala** [comment] 2020-05-17 00:49
CUDA builds are passing now. I created a separate issue (https://github.com/IntelligentSoftwareSystems/Galois/issues/228) for Fedora-clang build error. We can close this issue if it is fine.

**Comment by vishweshjatala** [comment] 2020-05-19 15:28
PR https://github.com/IntelligentSoftwareSystems/Galois/issues/194 is merged. Closing it.

**Closed by vishweshjatala** 2020-05-19 15:28 UTC
