### ISSUE TITLE
Why running SGD with multiple hosts return segfault?

### ISSUE THREAD

**Issue by WyjAloneSmile** [IntelligentSoftwareSystems/Galois#39] opened 2019-06-24 13:18 UTC
I have an bipartite graph with 11 nodes and 10 edges. The edgelist of this graph is:
1 6 1
2 6 1
2 7 1
3 7 1
3 8 1
4 8 1
4 9 1
5 9 1
5 10 1
0 10 1
I convert it to .gr with -edgelist2gr.
When I used it to run SGD in one host ,the program run successfully,but when I used it to run SGD in two hosts, the program return segfaults.
[0] InitializeGraph::go called
[1] InitializeGraph::go called
yhrun: error: cn7420: task 1: Segmentation fault

When program run
_graph.sync<writeSource, readAny, Reduce_set_latent_vector>("InitializeGraph");
program return segfaults.
How to solve it?

**Comment by gurbinder533** [comment] 2019-06-29 03:40
Hello, 
We have been able to reproduce this error and are working on the fix. We will push the changes as soon as possible and let you know.

**Comment by Yang-YiFan** [comment] 2019-07-17 05:22
I've also encountered a similar issue. The program went segmentation fault on both gr and sgr format input.

**Comment by l-hoang** [comment] 2019-10-18 16:33
Hello.

@WyjAloneSmile May you give me the command you used to convert your edgelist to the gr format as well as the command line you used to run sgd?

@Yang-YiFan Please open a separate issue with more details such as the command line used, graph used, etc, and I can take a look at your problem.

Thank you.

**Comment by WyjAloneSmile** [comment] 2019-10-20 15:19
> Hello.
> 
> @WyjAloneSmile May you give me the command you used to convert your edgelist to the gr format as well as the command line you used to run sgd?
> 
> @Yang-YiFan Please open a separate issue with more details such as the command line used, graph used, etc, and I can take a look at your problem.
> 
> Thank you.

convert edgelist to gr:  ./graph-convert input_graph output_graph -edgelist2gr -edgeType=int32
run SGD: yhrun -N 2 -n 2 -c 1  ./sgd input_gr  -runs=1 -t=1 -DECAY_RATE=0.5 -LAMBDA=0.001 -LEARNING_RATE=0.001 -maxIterations=1000

**Comment by l-hoang** [comment] 2019-10-21 16:56
Hello @WyjAloneSmile.

Please try using "-edgeType=float64" instead of "-edgeType=int32". The distributed SGD graph expects a double for its datatype.

I am not able to reproduce the exact error you are seeing, but using int32 does cause the program to hang on my end. Using float64 causes it to run to completion correctly.

Let me know how it goes.

Thanks,
Loc

**Comment by l-hoang** [comment] 2019-12-04 18:46
I'll be closing this issue unless there are still problems. In that case, please reopen it.

**Closed by l-hoang** 2019-12-04 18:46 UTC
