### ISSUE TITLE
GMetis test failure (run-small1-gmetis-16)

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#116] opened 2020-04-09 19:22 UTC
Example here:
https://circleci.com/gh/IntelligentSoftwareSystems/Galois/5326

No useful output I can tell.

We should probably set up core dumps to help debug better. I've already set this up in KatanaGraph/katana and it has been pretty helpful for debugging these types of issues.

**Comment by roshandathathri** [comment] 2020-05-22 15:48
I cannot reproduce this issue on our local machines. It might be a non-deterministic bug. The crash occurred only one of the inputs and threads (neither max nor min) test case. All the other tests passed. I ran the tests 100s of times for the same inputs with different number of threads - all the tests passed.

I would suggest re-enabling the test and checking if the issue is still reproducible.

**Comment by insertinterestingnamehere** [comment] 2020-05-22 16:26
Trying out re-enabling this in https://github.com/IntelligentSoftwareSystems/Galois/pull/247.

**Comment by insertinterestingnamehere** [comment] 2020-05-22 16:41
Trying this out locally, I suspect this is a memory use problem. For example, on one of our 40 core machines `(ulimit -v 4000000 && ./gmetis "/net/ohm/export/iss/inputs/reference/structured/rome99.gr" 4 -t=20)` fails consistently. The CI machines only have 4GB of ram. Given that, it may make more sense to just keep the failing test disabled in CI for the time being.

**Comment by ddn0** [comment] 2020-05-22 16:50
given that: perhaps we should close this ticket or refocus this ticket to updating gmetis and/or core libgalois to have better behavior during OOM (like at least printing an error message or something)?

**Comment by roshandathathri** [comment] 2020-05-22 16:50
Thanks for catching that, Ian.

It likely is due to the preAlloc() call. The only apps that are using galois::runtime::numPagePoolAllocTotal() to preAlloc() are bipart and gmetis. I notice that bipart test also has been marked as NOT_QUICK. Is it due to a memory issue as well?

We can fix preAlloc() to reduce the memory footprint.

**Comment by roshandathathri** [comment] 2020-05-22 16:51
> core libgalois to have better behavior during OOM (like at least printing an error message or something)?

Yes, this would be great.

**Comment by insertinterestingnamehere** [comment] 2020-05-22 16:53
Hmm I'm not sure my command line is the right way to reproduce this issue. The backtrace from the allocation failure just points to the runtime failing to initialize at all with the restricted memory. Unfortunately that means we still don't have a reliable way to reproduce this.

All that said, yes, bipart had a similar issue and this still could be a memory limit issue. We'll see if the CI tests can give us any ideas on how to reproduce this reliably.

**Comment by roshandathathri** [comment] 2020-05-22 16:57
On a different machine, it didn't crash with "ulimit -v 4000000" but it aborted with "ulimit -v 2000000" and it gave the error:
ERROR: /h2/roshan/SourceCode/Galois/libgalois/src/PageAlloc.cpp:81: Cannot allocate memory: Out of Memory
ERROR: /h2/roshan/SourceCode/Galois/libgalois/src/PageAlloc.cpp:81: Cannot allocate memory: Out of Memory

**Comment by insertinterestingnamehere** [comment] 2020-05-22 17:18
Yah, at least in some out-of-memory cases it does actually say what's wrong. I'm a bit surprised that we run out of memory even with several GB available. 4GB is a small system, but it's surprising that we outright crash in that case.

**Comment by roshandathathri** [comment] 2020-05-22 20:17
On one of our 56-core machines, I ran the same command that Ian used `(ulimit -v 4000000 && ./gmetis "/net/ohm/export/iss/inputs/reference/structured/rome99.gr" 4 -t=20)` and it crashes.

I get this message if huge pages are reserved in the system:
```
ERROR: /h2/roshan/SourceCode/Galois/libgalois/src/PageAlloc.cpp:81: Cannot allocate memory: Out of Memory
Aborted (core dumped)
```

I do not get any message if huge pages are not reserved in the system:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
```

I will look into reducing preAlloc() for gmetis before we close this issue. I think we should create a separate issue for reporting messages when out of memory.

**Comment by roshandathathri** [comment] 2020-05-23 00:40
I commented out the preAlloc() line and I still get the same issue as above, so I think we can close this issue and let the rome99 test be denoted as NOT_QUICK. 

We can create a separate issue for the out of memory message.

**Closed** 2020-05-27 19:40 UTC
