### ISSUE TITLE
Investigate slow dist tests

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#138] opened 2020-04-21 20:26 UTC
Certain lonestardist tests are marked `NOT_QUICK` because they will timeout when run in parallel:
- bfs_pull
- cc_push
- kcore_pull
- sssp_push

**Comment by l-hoang** [comment] 2020-04-24 00:08
Do you have an example of some output for the slow runs? If I recall these run fine when run locally, so it might not be that their slow but that there is some other underlying issue going on.

**Comment by ddn0** [comment] 2020-04-24 00:41
The way I came up with this list was to:
- run `ctest -L quick --parallel`
- walk away
- notice that there was a test that continued running for a least a minute (IIRC, the tests actually looked stuck to me: even after minutes, no progress was made).
- mark it as `NOT_QUICK`
- repeat

In general, we are aiming for our quick tests to take no more than a few seconds to run (perhaps 30 seconds on the outside), so one resolution to this issue (assuming there isn't an actual bug) would be to find comparable inputs for the above applications that do run within this window and still exercise the relevant functionality.

**Comment by l-hoang** [comment] 2020-05-02 00:54
It's very likely that these were hangs caused by dist stats; should get fixed by PR #147.

**Closed** 2020-05-07 16:05 UTC
