### ISSUE TITLE
Internal compiler error in CUDA build

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#195] opened 2020-05-07 20:22 UTC
Observed with CUDA 10.1 and 10.2

```
/data/lonestar/analytics/gpu/pta/andersen.cu(1379): internal error: assertion failed: conv_glvalue_expr_to_prvalue: bad expr (/dvs/p4/build/sw/rel/gpu_drv/r418/trd418_98/drivers/compiler/edg/edg_5.0/src/exprutil.c, line 20215)


1 catastrophic error detected in the compilation of "/tmp/tmpxft_00001c6f_00000000-4_pta.cpp4.ii".
````

Example: https://app.circleci.com/pipelines/github/IntelligentSoftwareSystems/Galois/384/workflows/ea8967fe-9e9f-4bea-9bb3-7eb4be31418d/jobs/7626/steps

**Comment by vishweshjatala** [comment] 2020-05-14 21:24
This test builds correctly on our local machine. It seems to be failing only on Ubuntu18.04. I don't have access to Ubuntu 18.04. Is there a way we can try to  reproduce it?

**Comment by ddn0** [comment] 2020-05-14 21:31
See https://github.com/IntelligentSoftwareSystems/Galois/issues/194

**Comment by vishweshjatala** [comment] 2020-05-17 00:50
CUDA builds are passing now. I created a separate issue (https://github.com/IntelligentSoftwareSystems/Galois/issues/228) for Fedora-clang build error. We can close this issue if it is fine.

**Comment by vishweshjatala** [comment] 2020-05-19 15:27
PR https://github.com/IntelligentSoftwareSystems/Galois/issues/194 is merged. Closing it.

**Closed by vishweshjatala** 2020-05-19 15:27 UTC
