### ISSUE TITLE
bipart segfault

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#171] opened 2020-05-04 22:43 UTC
```
 42/200 Test  #35: run-small1-bipart-1 .....................................................***Exception: SegFault  0.31 sec
```
No other context from the crash

https://travis-ci.org/github/IntelligentSoftwareSystems/Galois/builds/683115972

**Comment by insertinterestingnamehere** [comment] 2020-05-05 00:21
I'll stop running the test in CI to keep things running there.

**Comment by insertinterestingnamehere** [comment] 2020-05-05 00:23
@Breakinbad this one's yours can you look into it? It looks like it's somewhat nondeterministic in many configurations, but I'm able to easily reproduce the crash on our development machines by configuring with

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
```

**Comment by insertinterestingnamehere** [comment] 2020-05-05 00:25
Actually, I'm seeing the failure consistently even just when doing a debug build with gcc. Specifically, configuring with
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
```
after sourcing `scripts/iss_load_modules.sh`.

**Comment by insertinterestingnamehere** [comment] 2020-05-06 16:42
Fixed in master. Thanks @Breakinbad!

**Closed by insertinterestingnamehere** 2020-05-06 16:42 UTC
